# Generated by Django 4.2.1 on 2023-05-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_clientimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('ph_number', models.IntegerField(blank=True, null=True)),
                ('whatsapp_link', models.CharField(blank=True, max_length=500, null=True)),
                ('insta_link', models.CharField(blank=True, max_length=500, null=True)),
                ('facebook_link', models.CharField(blank=True, max_length=500, null=True)),
                ('twitter_link', models.CharField(blank=True, max_length=500, null=True)),
                ('utube_link', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
