# Generated by Django 4.2.1 on 2023-05-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0003_sitedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedetails',
            name='footer_copyright',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
