# Generated by Django 4.2.1 on 2023-05-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0004_sitedetails_footer_copyright'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_images', models.ImageField(blank=True, null=True, upload_to='banner_pictures')),
                ('Banner_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
